name: Create key.properties
  run: |
    echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
    echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
    echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
    echo "storeFile=app/hajez-release.jks" >> android/key.properties

name: Decode keystore
  run: |
    echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/hajez-release.jks

- name: Build APK
  run: flutter build apk --release
