- name: Install dependencies
        working-directory: hajez_flutter
        run: flutter pub get

      - name: Create key.properties
        working-directory: hajez_flutter
        run: |
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=app/hajez-release.jks" >> android/key.properties

      - name: Decode keystore
        working-directory: hajez_flutter
        run: |
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/hajez-release.jks

      - name: Build APK
        working-directory: hajez_flutter
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hajez-release
          path: hajez_flutter/build/app/outputs/flutter-apk/app-release.apk
